services:
  mysql:
    image: mysql:9
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "!Passw0rd"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pYourStrong!Passw0rd"]
      interval: 30s
      timeout: 10s
      retries: 5
