services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    hostname: sqlserver
    environment:
      SA_PASSWORD: "!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '!Passw0rd' -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
